-- =====================================================================
-- V1__esquema_inicial.sql  |  PostgreSQL 14+
-- Personas (superclase) -> clientes, admin | deudas | pagos | total_dinero
-- Reglas:
--   * Dinero SIEMPRE NUMERIC(14,2). Nunca REAL / DOUBLE PRECISION / FLOAT.
--   * Nada de DELETE: borrado lógico con activo (1 = activo, 0 = inactivo).
-- =====================================================================

-- ---------------------------------------------------------------------
-- SUPERCLASE: personas   (tipo: 1 = cliente, 2 = admin)
-- ---------------------------------------------------------------------
CREATE TABLE personas (
    id_persona          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo                INTEGER      NOT NULL,
    nombre              VARCHAR(80)  NOT NULL,
    apellido            VARCHAR(80)  NOT NULL,
    documento           VARCHAR(20)  NOT NULL,
    correo              VARCHAR(120) NOT NULL,
    telefono            VARCHAR(20),
    activo              SMALLINT     NOT NULL DEFAULT 1,
    fecha_creacion      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_personas_documento UNIQUE (documento),
    CONSTRAINT uq_personas_correo    UNIQUE (correo),
    CONSTRAINT uq_personas_id_tipo   UNIQUE (id_persona, tipo),
    CONSTRAINT ck_personas_tipo      CHECK (tipo IN (1, 2)),
    CONSTRAINT ck_personas_activo    CHECK (activo IN (0, 1)),
    CONSTRAINT ck_personas_correo_minuscula CHECK (correo = lower(correo))
);

-- ---------------------------------------------------------------------
-- SUBCLASE: clientes. La FK compuesta (id_persona, tipo) garantiza que
-- solo una persona de tipo 1 pueda ser cliente.
-- ---------------------------------------------------------------------
CREATE TABLE clientes (
    id_persona BIGINT       PRIMARY KEY,
    tipo       INTEGER      NOT NULL DEFAULT 1,
    direccion  VARCHAR(150),
    CONSTRAINT ck_clientes_tipo CHECK (tipo = 1),
    CONSTRAINT fk_clientes_persona FOREIGN KEY (id_persona, tipo)
        REFERENCES personas (id_persona, tipo)
);

-- ---------------------------------------------------------------------
-- SUBCLASE: admin (nivel_acceso: 1 = básico, 2 = intermedio, 3 = total)
-- ---------------------------------------------------------------------
CREATE TABLE admin (
    id_persona   BIGINT       PRIMARY KEY,
    tipo         INTEGER      NOT NULL DEFAULT 2,
    usuario      VARCHAR(50)  NOT NULL,
    clave_hash   VARCHAR(100) NOT NULL,
    nivel_acceso SMALLINT     NOT NULL DEFAULT 1,
    CONSTRAINT uq_admin_usuario UNIQUE (usuario),
    CONSTRAINT ck_admin_tipo    CHECK (tipo = 2),
    CONSTRAINT ck_admin_nivel   CHECK (nivel_acceso IN (1, 2, 3)),
    CONSTRAINT ck_admin_usuario_minuscula CHECK (usuario = lower(usuario)),
    CONSTRAINT fk_admin_persona FOREIGN KEY (id_persona, tipo)
        REFERENCES personas (id_persona, tipo)
);

-- ---------------------------------------------------------------------
-- deudas   (estado: 1 = pendiente, 2 = pagada)
-- ---------------------------------------------------------------------
CREATE TABLE deudas (
    id_deuda            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente          BIGINT        NOT NULL REFERENCES clientes (id_persona),
    id_admin            BIGINT        NOT NULL REFERENCES admin (id_persona),
    concepto            VARCHAR(150)  NOT NULL,
    monto_inicial       NUMERIC(14,2) NOT NULL,
    saldo_pendiente     NUMERIC(14,2) NOT NULL,
    fecha_emision       DATE          NOT NULL,
    fecha_vencimiento   DATE,
    estado              SMALLINT      NOT NULL DEFAULT 1,
    activo              SMALLINT      NOT NULL DEFAULT 1,
    fecha_actualizacion TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_deudas_monto   CHECK (monto_inicial > 0),
    CONSTRAINT ck_deudas_saldo   CHECK (saldo_pendiente >= 0 AND saldo_pendiente <= monto_inicial),
    CONSTRAINT ck_deudas_estado  CHECK (estado IN (1, 2)),
    CONSTRAINT ck_deudas_activo  CHECK (activo IN (0, 1)),
    CONSTRAINT ck_deudas_coherencia CHECK ((estado = 2) = (saldo_pendiente = 0)),
    CONSTRAINT ck_deudas_fechas  CHECK (fecha_vencimiento IS NULL OR fecha_vencimiento >= fecha_emision)
);
CREATE INDEX idx_deudas_cliente ON deudas (id_cliente, activo);

-- ---------------------------------------------------------------------
-- pagos: libro de abonos, INMUTABLE (solo INSERT; ver V2).
-- La clave de idempotencia evita cobrar dos veces el mismo abono.
-- ---------------------------------------------------------------------
CREATE TABLE pagos (
    id_pago             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_deuda            BIGINT        NOT NULL REFERENCES deudas (id_deuda),
    id_admin            BIGINT        NOT NULL REFERENCES admin (id_persona),
    monto               NUMERIC(14,2) NOT NULL,
    saldo_resultante    NUMERIC(14,2) NOT NULL,
    clave_idempotencia  VARCHAR(64)   NOT NULL,
    fecha_pago          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_pagos_idempotencia UNIQUE (clave_idempotencia),
    CONSTRAINT ck_pagos_monto  CHECK (monto > 0),
    CONSTRAINT ck_pagos_saldo  CHECK (saldo_resultante >= 0)
);
CREATE INDEX idx_pagos_deuda ON pagos (id_deuda, fecha_pago);

-- ---------------------------------------------------------------------
-- total_dinero: acumulado por cliente (lo recalcula la capa de servicios)
-- ---------------------------------------------------------------------
CREATE TABLE total_dinero (
    id_total            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente          BIGINT        NOT NULL REFERENCES clientes (id_persona),
    total_deuda         NUMERIC(14,2) NOT NULL DEFAULT 0,
    total_pagado        NUMERIC(14,2) NOT NULL DEFAULT 0,
    activo              SMALLINT      NOT NULL DEFAULT 1,
    fecha_actualizacion TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_total_cliente  UNIQUE (id_cliente),
    CONSTRAINT ck_total_deuda    CHECK (total_deuda  >= 0),
    CONSTRAINT ck_total_pagado   CHECK (total_pagado >= 0),
    CONSTRAINT ck_total_activo   CHECK (activo IN (0, 1))
);
